export default {
  GET_ALL_STAGES: 'GET_ALL_STAGES',
  GET_ALL_STAGES_SUCCESS: 'GET_ALL_STAGES_SUCCESS',
  GET_ALL_STAGES_FAILURE: 'GET_ALL_STAGES_FAILURE',

  ADD_NEW_STAGE: 'ADD_NEW_STAGE',
  ADD_NEW_STAGE_SUCCESS: 'ADD_NEW_STAGE_SUCCESS',
  ADD_NEW_STAGE_FAILURE: 'ADD_NEW_STAGE_FAILURE',
  CLEAR_ADD_NEW_STAGE_MESSAGE: 'CLEAR_ADD_NEW_STAGE_MESSAGE',

  GET_ALL_TASK: 'GET_ALL_TASK',
  GET_ALL_TASK_SUCCESS: 'GET_ALL_TASK_SUCCESS',
  GET_ALL_TASK_FAILURE: 'GET_ALL_TASK_FAILURE',

  ADD_NEW_TASK: 'ADD_NEW_TASK',
  ADD_NEW_TASK_SUCCESS: 'ADD_NEW_TASK_SUCCESS',
  ADD_NEW_TASK_FAILURE: 'ADD_NEW_TASK_FAILURE',
  CLEAR_ADD_NEW_TASK_MESSAGE: 'CLEAR_ADD_NEW_TASK_MESSAGE',

  UPDATE_PRIORITY: 'UPDATE_PRIORITY',
  UPDATE_PRIORITY_SUCCESS: 'UPDATE_PRIORITY_SUCCESS',
  UPDATE_PRIORITY_FAILURE: 'UPDATE_PRIORITY_FAILURE',
};
